name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["💻 aspect: code", "🛠 goal: fix", "🚦 status: awaiting triage"]
assignees:
  - krishdevdb
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Add a detailed description of the bug report.
      placeholder: A detailed description of the bug report.
      value: "I found this error in this project where ..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should be expected?
      value: "I expected that..."
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What actually happened?
      placeholder: What should be happen?
      value: "Instead of [what should happen](#expected-behavior), I find..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How can someone reproduce the behavior?
      description: Steps to reproduce the behavior you were facing.
      placeholder: How can someone reproduce the behavior you were facing?
      value: |
        1. Goto...
        2. Do...
        3. Now...
        4. Finally...
    validations:
        required: true

  - type: input
    id: environment
    attributes:
      label: What was you environment (os, browser, runtime, etc)?
      description: The environment (os, browser, runtime, etc) which faced the bug described
      placeholder: What was environment (os, browser, runtime, etc) while you were facing the issue?
      value: "Ubuntu Latest, Chrome Latest, Node14..."
    validations:
        required: true

  - type: checkboxes
    id: contributing
    attributes:
      label: Contributing
      description: You accept that you've read the [Contributing](https://github.com/resetercss/reseter.css/blob/main/contributing.md)
      options:
        - label: I have read the project's contribution guidelines.
          required: true
    validations:
        required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/resetercss/reseter.css/blob/main/code_of_conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    validations:
        required: true

  - type: textarea
    attributes:
        label: Anything else?
        description: |
          Links? References? Anything that will give us more context about the issue you are encountering!
      
          Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
        required: false
=======
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["💻 aspect: code", "🛠 goal: fix", "🚦 status: awaiting triage"]
assignees:
  - krishdevdb
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Add a detailed description of the bug report.
      placeholder: A detailed description of the bug report.
      value: "I found this error in this project where ..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should be expected?
      value: "I expected that..."
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What actually happened?
      placeholder: What should be happen?
      value: "Instead of [what should happen](#expected-behavior), I find..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How can someone reproduce the behavior?
      description: Steps to reproduce the behavior you were facing.
      placeholder: How can someone reproduce the behavior you were facing?
      value: |
        1. Goto...
        2. Do...
        3. Now...
        4. Finally...
    validations:
        required: true

  - type: input
    id: environment
    attributes:
      label: What was you environment (os, browser, runtime, etc)?
      description: The environment (os, browser, runtime, etc) which faced the bug described
      placeholder: What was environment (os, browser, runtime, etc) while you were facing the issue?
      value: "Ubuntu Latest, Chrome Latest, Node14..."
    validations:
        required: true

  - type: checkboxes
    id: contributing
    attributes:
      label: Contributing
      description: You accept that you've read the [Contributing](https://github.com/krishdevdb/.github/blob/main/contributing.md)
      options:
        - label: I have read the project's contribution guidelines.
          required: true
    validations:
        required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/krishdevdb/.github/blob/main/code_of_conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    validations:
        required: true

  - type: textarea
    attributes:
        label: Anything else?
        description: |
          Links? References? Anything that will give us more context about the issue you are encountering!
      
          Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
        required: false
